# Generated by Django 6.0.6 on 2026-07-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'permissions': [('export_brand', 'Can export brand'), ('print_brand', 'Can print brand')], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('export_customer', 'Can export customer'), ('print_customer', 'Can print customer')]},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date'], 'permissions': [('export_invoice', 'Can export invoice'), ('print_invoice', 'Can print invoice')]},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('export_product', 'Can export product'), ('print_product', 'Can print product')], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ['name'], 'permissions': [('export_productgroup', 'Can export product group'), ('print_productgroup', 'Can print product group')], 'verbose_name': 'Product Group', 'verbose_name_plural': 'Product Groups'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'permissions': [('export_supplier', 'Can export supplier'), ('print_supplier', 'Can print supplier')], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
    ]
