# Generated by Django 6.0.6 on 2026-07-13 01:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_invoice_estado_invoice_saldo_invoice_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='customer',
            name='document_type',
            field=models.CharField(blank=True, choices=[('CEDULA', 'Cédula'), ('RUC', 'RUC')], default='CEDULA', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('PRODUCTO', 'Producto'), ('SERVICIO', 'Servicio')], default='PRODUCTO', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='IVA (%)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='document_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RUC/Cédula'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='document_type',
            field=models.CharField(blank=True, choices=[('CEDULA', 'Cédula'), ('RUC', 'RUC')], default='RUC', max_length=10),
        ),
    ]
