# Generated by Django 6.0.6 on 2026-07-11 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchasing', '0004_purchase_estado_purchase_saldo_purchase_tipo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada')], default='PENDIENTE', max_length=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='purchasing.purchase')),
            ],
            options={
                'verbose_name': 'Cuota de Compra',
                'verbose_name_plural': 'Cuotas de Compra',
                'ordering': ['compra', 'numero'],
                'unique_together': {('compra', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='PagoCuotaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacion', models.TextField(blank=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='creditos_compras.cuotacompra')),
            ],
            options={
                'verbose_name': 'Pago de Cuota de Compra',
                'verbose_name_plural': 'Pagos de Cuota de Compra',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
