# Generated by Django 6.0.6 on 2026-07-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_purchase_unique_supplier_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date'], 'permissions': [('export_purchase', 'Can export purchase'), ('print_purchase', 'Can print purchase')], 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
    ]
