# Generated by Django 6.0.6 on 2026-07-10 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0007_invoice_estado_invoice_saldo_invoice_tipo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada')], default='PENDIENTE', max_length=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Cuota de Venta',
                'verbose_name_plural': 'Cuotas de Venta',
                'ordering': ['factura', 'numero'],
                'unique_together': {('factura', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='PagoCuotaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacion', models.TextField(blank=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='creditos_ventas.cuotaventa')),
            ],
            options={
                'verbose_name': 'Pago de Cuota',
                'verbose_name_plural': 'Pagos de Cuota',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
